services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automation-db-service
    ports:
      - "${PORT:-5001}:${PORT:-5001}" 
    env_file:
      - .env 
    restart: always
